on:
  release:
    types:
      - created
name: Generate distributables v2
jobs:
  generate-artifacts:
    name: Generate artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          ref: master
      - name: Get current tag
        uses: olegtarasov/get-tag@v2
        id: tag_name
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Install pipreqs
        run: pip3 install pipreqs
      - name: Generate the artifacts
        run: |
          make clean
          make dist -B VERSION=${{ steps.tag_name.outputs.tag }}
      - name: Attach artifacts to release
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: keycov.zip
